FROM openjdk:11

LABEL maintainer="MUDITMANGAL"
ADD target/process-pension-microservice-0.0.1-SNAPSHOT.jar process-pension-microservice.jar
ENTRYPOINT ["java","-jar","process-pension-microservice.jar"]